pmOnFail: ignore

minimumReleaseAgeExclude:
  - '@next/*'
  - next

allowBuilds:
  esbuild: true
  workerd: true
  sharp: true
  '@google/genai': set this to true or false
  protobufjs: set this to true or false
